name: Deploy site files

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps:
      - name: =>> Checkout Branch # 1，下载代码仓库
        uses: actions/checkout@v2
        
      - name: =>> Install Deps & Build # 2, 安装依赖并打包
        run: |
          yarn
          yarn build
          
      - name: =>> Deploy To Server # 3，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SERVER_PORT: "22" # SSH端口
          FOLDER: ./dist # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.REMOTE_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.REMOTE_USER }} # 引用配置，服务器登录名
          SERVER_DESTINATION: /home/sites/junxio/ # 部署到目标文件夹
